### PR TITLE
Enables bem linting

### PR DESCRIPTION
**Pull request by jeffjewiss**
I thought it would be useful to enable the utility class linting. Cheers!

### CODE REVIEW

**Comment by simonsmith** [comment]
Good catch. Think I've probably overlooked this on other packages too. Thanks.

**Comment by simonsmith** [comment]
@jeffjewiss Might be better to remove the `plugins` property entirely, must be a mistake from me:

``` js
"postcss-reporter": {
    "throwError": true
  }
```

If you could also amend the commit message to be present tense, then I'll get it merged :+1:

**Comment by jeffjewiss** [comment]
You're welcome, thanks for all the great work on SUITCSS!

Okay cool, thanks for looking into this. I hadn't gone through the
SUITCSS processor and the default plugin setup. I've updated the commit,
is that what you meant for the commit message?

On 02/22, Simon Smith wrote:
> @jeffjewiss Might be better to remove the `plugins` property entirely, must be a mistake from me:
>
> ``` js
> "postcss-reporter": {
>     "throwError": true
>   }
> ```
>
> If you could also amend the commit message to be present tense, then I'll get it merged :+1:
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/suitcss/utils-display/pull/11#issuecomment-187404864

--
Jeff Jewiss

**Comment by simonsmith** [comment]
That's perfect. Thanks @jeffjewiss

**Pull request merged**
